import Head from 'next/head'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Navbar from '../nav/top'
import Footer from '@/nav/footer'
import styles from '../styles/Home.module.css'
import Image from 'next/image'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title className={'styles.title'}>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='content'>  

      <Image src="/ferrari14.jpg" height={77} width={128} alt={'logo'}/>
        
        <h1 className='title'>Welcome Home</h1>
        <Navbar/>

        <p className={styles.text}>This is where we serve hot tea together with great Content</p>
        <Link href={'/ninjas'} className={styles.btn}>Ninja List</Link>
        <Link href={'/ninjas/mapicha'} className={styles.btn}> Pictures</Link>
        <Footer/>
      </div>
      
      
    </>
  )
}
